### ISSUE TITLE
Modals API broken?

### ISSUE THREAD

**Issue by hyblocker** [strencher-kernel/pc-compat#25] opened 2022-05-10 21:41 UTC
powerCord's modal api doesn't seem to be emulated properly. The `powercord.modal` prop in the `powercord` global seems to be exposing fields properly, but requiring `powercord/modal` seems to return different functions.

**Comment by localip** [comment] 2022-06-26 20:03
Cannot reproduce, both open the modal fine.
Closing for now.

**Closed by localip** 2022-06-26 20:03 UTC
